[phases.setup]
nixPkgs = ["python312", "nodejs-18_x", "pnpm"]

[phases.install]
cmds = [
  "pnpm install",
  "pip install -r pizzaz_server_python/requirements.txt",
  "pip install -r solar-system_server_python/requirements.txt",
  "pip install python-dotenv"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "uvicorn unified_server:app --host 0.0.0.0 --port $PORT"
