[phases.setup]
nixPkgs = ["python312", "nodejs-18_x", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile",
  "python -m pip install --upgrade pip",
  "python -m pip install -r pizzaz_server_python/requirements.txt",
  "python -m pip install -r solar-system_server_python/requirements.txt",
  "python -m pip install python-dotenv"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "uvicorn unified_server:app --host 0.0.0.0 --port $PORT"
